### ISSUE TITLE
Compilation error installing from crates.io

### ISSUE THREAD

**Issue by wycats** [foresterre/cargo-publish-workspace#18]
TLDR:

```
   Compiling cargo-publish-workspace v0.18.1
error[E0599]: no variant or associated item named `VersionlessSubcommands` found for enum `AppSettings` in the current scope
  --> /home/wycats/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-publish-workspace-0.18.1/src/arguments.rs:37:33
   |
37 |     global_setting(AppSettings::VersionlessSubcommands),
   |                                 ^^^^^^^^^^^^^^^^^^^^^^ variant or associated item not found in `AppSettings`
```

This doesn't happen when installing from git, and the code it points to is no longer in the codebase. Perhaps a semver-violating breaking change? Either way, it seems like it would be good to do another release.

**Comment by foresterre** [comment]
Thanks for the report, I'll have a look!

**Comment by foresterre** [comment]
What I think that happened:
* The current version of `cargo-publish-workspace` on crates.io depends on `clap` version `3.0.0-beta.2`.
* I did not lock the beta version to this exact version
* Clap released two new beta releases, one of which contains the above breaking change
* Cargo's version resolution pulls in `clap` version `3.0.0-beta.4` 
* This was fixed (for now, no version locking here either) in https://github.com/foresterre/cargo-publish-workspace/commit/13d571ea5a619ae688115ac45cdf4a3984ebf71e#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542, which is not published yet

**Comment by foresterre** [comment]
Released as https://crates.io/crates/cargo-publish-workspace/0.19.0

<details>
<summary>tested building from crates.io</summary>

❯ cargo install cargo-publish-workspace                                 02:10:19
    Updating crates.io index
  Downloaded cargo-publish-workspace v0.19.0
  Downloaded 1 crate (13.8 KB) in 1.01s
  Installing cargo-publish-workspace v0.19.0
  Downloaded smallvec v1.7.0
  Downloaded serde_json v1.0.68
  Downloaded pathdiff v0.2.1
  Downloaded 3 crates (149.6 KB) in 0.29s
   Compiling proc-macro2 v1.0.29
   Compiling unicode-xid v0.2.2
   Compiling autocfg v1.0.1
   Compiling syn v1.0.77
   Compiling serde_derive v1.0.130
   Compiling version_check v0.9.3
   Compiling serde v1.0.130
   Compiling libc v0.2.103
   Compiling ryu v1.0.5
   Compiling target-lexicon v0.12.2
   Compiling serde_json v1.0.68
   Compiling semver v1.0.4
   Compiling hashbrown v0.11.2
   Compiling memchr v2.4.1
   Compiling camino v1.0.5
   Compiling unicode-segmentation v1.8.0
   Compiling target-spec v0.8.0
   Compiling itoa v0.4.8
   Compiling smallvec v1.7.0
   Compiling either v1.6.1
   Compiling fixedbitset v0.4.0
   Compiling anyhow v1.0.44
   Compiling unicode-width v0.1.9
   Compiling bytes v1.1.0
   Compiling linked-hash-map v0.5.4
   Compiling termcolor v1.1.2
   Compiling strsim v0.10.0
   Compiling lazy_static v1.4.0
   Compiling once_cell v1.8.0
   Compiling supercow v0.1.0
   Compiling pathdiff v0.2.1
   Compiling bitflags v1.3.2
   Compiling nested v0.1.1
   Compiling vec_map v0.8.2
   Compiling os_str_bytes v3.1.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.7.0
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling itertools v0.10.1
   Compiling textwrap v0.14.2
   Compiling heck v0.3.3
   Compiling cfg-expr v0.9.0
   Compiling combine v4.6.1
   Compiling quote v1.0.9
   Compiling time v0.1.44
   Compiling atty v0.2.14
   Compiling petgraph v0.6.0
   Compiling chrono v0.4.19
   Compiling clap_derive v3.0.0-beta.4
   Compiling clap v3.0.0-beta.4
   Compiling toml_edit v0.2.1
   Compiling cargo-platform v0.1.2
   Compiling cargo_metadata v0.14.0
   Compiling guppy v0.10.1
   Compiling cargo-publish-workspace v0.19.0
    Finished release [optimized] target(s) in 45.45s
   Replacing /home/al/.cargo/bin/cargo-publish-workspace
    Replaced package `cargo-publish-workspace v0.18.1` with `cargo-publish-workspace v0.19.0` (executable `cargo-publish-workspace`)

</details>
